##  filenames
##  directory
##  shapefile
FEATURECODE<-"D:\\BuiltVerification\\featureCodes_en.txt"
FEATURES   <- "D:\\BuiltVerification\\allCountries.txt"
LANDCLASS  <-"D:\\GlobalHistoricalClimateNetwork\\Rasters\\LandCover\\ESACCI-LC-L4-LCCS-Map-300m-P1Y-2015-v2.0.7.tif"
AIRPORTS   <-"D:\\GlobalHistoricalClimateNetwork\\Rasters\\airports.csv"
NLCD <-"D:\\GlobalHistoricalClimateNetwork\\Rasters\\NLCD_2016_Impervious_L48_20190405\\NLCD_2016_Impervious_L48_20190405.img"
SELECTEDAIR<-"D:\\BuiltVerification\\AirportSelected.csv"
GEONAMES<- "D:\\BuiltVerification\\GeonamesData.csv"
SELECTFEATURES<- "D:\\BuiltVerification\\SelectedFeatureDescription.csv"
AIRPORTLC_NLCD<-"D:\\BuiltVerification\\AirportLC_NLCD.csv"
GHSDIR <- "D:\\GlobalHistoricalClimateNetwork\\Rasters\\GHSBuilt\\V2-0"
AIRPORT_GHS<-"D:\\BuiltVerification\\AirportBuiltGHS.csv"
SPOTDIR<-"D:\\GlobalHistoricalClimateNetwork\\Rasters\\ESM_BUILT_VHR2015_EUROPE_R2019_3035_02_V1_0"
AIRPORT_SPOT<-"D:\\BuiltVerification\\AirportBuiltSpot.csv"
CHINA_INDEX<-"D:\\BuiltVerification\\Chinese30mIndex.csv"
CHINA_BUILT30M <-"D:\\BuiltVerification\\AirportBuiltCH30m.csv"
GMSDIR <- "D:\\GlobalHistoricalClimateNetwork\\Rasters\\GMIS2"
GISDIR <-"D:\\GlobalHistoricalClimateNetwork\\Rasters\\GIS\\Global Impervious Surfaces products"
AIRPORT_GIS<- "D:\\BuiltVerification\\AirportBuiltGIS.csv"